# Generated by Django 6.0.1 on 2026-01-13 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Address',
                'verbose_name_plural': 'Saved Addresss',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('reviewed', 'Reviewed'), ('shipping_selected', 'Shipping Selected'), ('purchased', 'Purchased'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('label_format', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('length_inches', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('width_inches', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_inches', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_lbs', models.IntegerField(default=0)),
                ('weight_oz', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('from_first_name', models.CharField(blank=True, max_length=50)),
                ('from_last_name', models.CharField(blank=True, max_length=50)),
                ('from_address_line1', models.CharField(blank=True, max_length=255)),
                ('from_address_line2', models.CharField(blank=True, max_length=255)),
                ('from_city', models.CharField(blank=True, max_length=100)),
                ('from_zip_code', models.CharField(blank=True, max_length=10)),
                ('from_state', models.CharField(blank=True, max_length=2)),
                ('to_first_name', models.CharField(max_length=50)),
                ('to_last_name', models.CharField(blank=True, max_length=50)),
                ('to_address_line1', models.CharField(max_length=255)),
                ('to_address_line2', models.CharField(blank=True, max_length=255)),
                ('to_city', models.CharField(max_length=100)),
                ('to_zip_code', models.CharField(max_length=10)),
                ('to_state', models.CharField(max_length=2)),
                ('weight_lbs', models.IntegerField(default=0)),
                ('weight_oz', models.IntegerField(default=0)),
                ('length_inches', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('width_inches', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_inches', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('phone_num1', models.CharField(blank=True, max_length=20)),
                ('phone_num2', models.CharField(blank=True, max_length=20)),
                ('order_no', models.CharField(blank=True, max_length=50)),
                ('item_sku', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('incomplete', 'Incomplete'), ('error', 'Error')], default='valid', max_length=20)),
                ('shipping_service', models.CharField(blank=True, choices=[('priority', 'Priority Mail'), ('ground', 'Ground Shipping')], max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.batch')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.package')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
    ]
