# Generated by Django 6.0.1 on 2026-01-13 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['name'], 'verbose_name': 'Saved Address', 'verbose_name_plural': 'Saved Addresss'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batchs'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['name'], 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shipment', 'verbose_name_plural': 'Shipments'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='package',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='from_address_line1',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='from_address_line2',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='from_first_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='from_last_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='from_state',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='from_zip_code',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='height_inches',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='item_sku',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='length_inches',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='phone_num1',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='phone_num2',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='to_address_line1',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='to_address_line2',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='to_city',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='to_first_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='to_last_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='to_state',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='to_zip_code',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='weight_lbs',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='weight_oz',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='width_inches',
        ),
        migrations.AddField(
            model_name='address',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ship_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_from_addresses', to='core.address'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ship_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_to_addresses', to='core.address'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='core.package'),
        ),
    ]
