# Generated by Django 6.0.1 on 2026-01-13 07:27

from django.db import migrations


def create_sample_addresses(apps, schema_editor):
    Address = apps.get_model("core", "Address")

    samples = [
        {
            "name": "Print TTS",
            "address_line1": "502 W Arrow Hwy, STE P",
            "city": "San Dimas",
            "state": "CA",
            "zip_code": "91773",
        },
        {
            "name": "Print TTS",
            "address_line1": "500 W Foothill Blvd, STE P",
            "city": "Claremont",
            "state": "CA",
            "zip_code": "91711",
        },
        {
            "name": "Print TTS",
            "address_line1": "1170 Grove Ave",
            "city": "Ontario",
            "state": "CA",
            "zip_code": "91764",
        },
    ]

    for data in samples:
        Address.objects.get_or_create(
            name=data["name"],
            address_line1=data["address_line1"],
            city=data["city"],
            state=data["state"],
            zip_code=data["zip_code"],
            saved=True,
            defaults={
                "first_name": "Print",
                "last_name": "TTS",
                "address_line2": "",
                "phone": "",
            },
        )


def create_sample_packages(apps, schema_editor):
    Package = apps.get_model("core", "Package")

    samples = [
        {
            "name": "Light Package",
            "length_inches": 6.00,
            "width_inches": 6.00,
            "height_inches": 6.00,
            "weight_lbs": 1,
            "weight_oz": 0,
        },
        {
            "name": "8 Oz Item",
            "length_inches": 4.00,
            "width_inches": 4.00,
            "height_inches": 4.00,
            "weight_lbs": 0,
            "weight_oz": 8,
        },
        {
            "name": "Standard Box",
            "length_inches": 12.00,
            "width_inches": 12.00,
            "height_inches": 12.00,
            "weight_lbs": 2,
            "weight_oz": 0,
        },
    ]

    for data in samples:
        Package.objects.get_or_create(
            name=data["name"],
            defaults={
                "length_inches": data["length_inches"],
                "width_inches": data["width_inches"],
                "height_inches": data["height_inches"],
                "weight_lbs": data["weight_lbs"],
                "weight_oz": data["weight_oz"],
                "sku": "",
                "saved":True
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_batch_options_batch_is_active_alter_batch_id"),
    ]

    operations = [
        migrations.RunPython(create_sample_addresses),
        migrations.RunPython(create_sample_packages),
    ]
