# Generated by Django 6.0.1 on 2026-01-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prepopulate_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='height_inches',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='length_inches',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='width_inches',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
