# Generated by Django 6.0.1 on 2026-01-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prepopulate_samples'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['created_at'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batchs'},
        ),
    ]
