# Generated by Django 6.0.1 on 2026-01-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_batch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['name'], 'verbose_name': 'Saved Address', 'verbose_name_plural': 'Saved Addresss'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batchs'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['name'], 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
    ]
