# Generated by Django 6.0.1 on 2026-01-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_package_height_inches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipping_service',
            field=models.CharField(choices=[('priority', 'Priority Mail'), ('ground', 'Ground Shipping')], default='ground', max_length=20),
        ),
    ]
