# Generated by Django 6.0.1 on 2026-01-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_shipment_shipping_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
