# Generated by Django 6.0.1 on 2026-01-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shipment_error_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['name'], 'verbose_name': 'Saved Address', 'verbose_name_plural': 'Saved Addresses'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
    ]
